"""The accent palette, and the stylesheet that paints it.

The nine colours arrive in palette.json, generated by ../palette.nix out of
pkgs/accent.nix — the same file modules/desktop.nix splices into labwc,
sfwbar, foot, fuzzel and mako, and the same file modules/applications.nix
rebuilds the GTK3 theme around. So the circle in the settings app is the
colour the desktop is about to be, rather than a second opinion about it.

Their names, their order and the default do not come through here: those are
the option's enum, and reach the app in schema.json like every other option's
do. What this file adds is only what a generated schema cannot know, which is
what each name looks like.

The CSS is generated too, for the same reason it is not a .css file shipped
beside the package: it *is* the palette, written out in the one syntax GTK
will draw a coloured circle from.
"""

from __future__ import annotations

import json
import re
from collections.abc import Mapping, Sequence
from typing import Final

from gi.repository import Gdk, Gtk

from . import paths

# The class on the bar, and the prefix of the class on each swatch in it.
# Both appear in the stylesheet below and nowhere else.
BAR_CLASS: Final = "accent-swatches"
SWATCH_PREFIX: Final = "accent-swatch-"

# What a name and a colour have to look like before either is written into a
# stylesheet. The file is generated, so neither of these should ever fire —
# but this is the one place in the application that turns something on disk
# into CSS, and pkgs/accent.nix takes the same precaution at the other end of
# the pipe for the same reason: a settings file people edit by hand is no
# reason for a stray character to reach a config file.
NAME: Final = re.compile(r"^[a-z][a-z0-9-]*$")
COLOUR: Final = re.compile(r"^#[0-9a-f]{6}$")

# Big enough to read as a colour rather than as a dot, which is the size
# GNOME draws its own at. The ring around the chosen one sits outside this,
# in the margin.
SIZE: Final = 22
SPACING: Final = 4

# Everything about a swatch that is not its colour. The radio node is what
# libadwaita would draw as a small circle with a dot in it; all of this is
# undoing that, so that what is left is a disc the size of a coin with the
# background colour the rules below give it. The outline is the ring around
# the chosen one — transparent here, coloured there, so that turning it on
# does not move anything.
_BAR: Final = f"""
.{BAR_CLASS} checkbutton {{
  min-width: 0;
  min-height: 0;
  padding: 0;
}}
.{BAR_CLASS} checkbutton radio {{
  min-width: {SIZE}px;
  min-height: {SIZE}px;
  margin: 2px;
  padding: 0;
  border: none;
  box-shadow: none;
  background-image: none;
  -gtk-icon-source: none;
  color: transparent;
  outline: 2px solid transparent;
  outline-offset: 2px;
}}
"""


def swatch_class(name: str) -> str:
    return f"{SWATCH_PREFIX}{name}"


def load() -> Mapping[str, str]:
    """palette.json, with anything that is not a name and a colour dropped.

    Dropped rather than raised over: a palette this application cannot read
    costs it the swatches and nothing else — swatch_colors below puts the
    dropdown back, and every accent is still reachable by name.
    """
    try:
        with open(paths.PALETTE, encoding="utf-8") as handle:
            raw = json.load(handle)
    except (OSError, ValueError):
        return {}
    if not isinstance(raw, dict):
        return {}

    palette: dict[str, str] = {}
    for name, value in raw.items():
        colour = value.lower() if isinstance(value, str) else ""
        if NAME.match(name) and COLOUR.match(colour):
            palette[name] = colour
    return palette


def swatch_colors(members: Sequence[str]) -> Mapping[str, str]:
    """A colour for every one of them, or nothing at all.

    Nothing at all is what puts the dropdown back. A bar of circles with a
    hole in it is worse than the list of names it replaced, and a member the
    palette has never heard of is exactly the case where its name is the only
    thing left that is still true about it.
    """
    palette = load()
    chosen = {name: palette[name] for name in members if name in palette}
    return chosen if len(chosen) == len(members) else {}


def stylesheet(palette: Mapping[str, str]) -> str:
    """The palette as CSS: a filled disc per colour, ringed when chosen.

    Every colour is stated for the checked and hovered states as well as the
    plain one, which is not redundancy: libadwaita styles `checkbutton
    radio:checked` itself — a more specific selector than
    `.accent-swatch-blue radio` — and fills it with the accent the theme is
    already using. Said any less specifically, the bar would come out as one
    colour nine times.
    """
    rules = [_BAR]
    for name, colour in palette.items():
        css = swatch_class(name)
        rules.append(
            f".{css} radio, .{css} radio:hover,\n"
            f".{css} radio:checked, .{css} radio:checked:hover "
            f"{{ background-color: {colour}; }}\n"
            # Chosen and focused look the same on purpose: arrowing through a
            # radio group chooses as it goes, so there is no third state to
            # tell apart, and the ring is legible on all nine.
            f".{css} radio:checked, .{css} radio:focus-visible "
            f"{{ outline-color: {colour}; }}"
        )
    return "\n".join(rules)


_provider: Gtk.CssProvider | None = None


def install(display: Gdk.Display) -> Gtk.CssProvider:
    """Put the stylesheet on the display, once, and hand it back.

    Once, because the palette cannot change while the application is running:
    it is a file in the store, generated with the build this copy came from.
    So a second caller gets the provider the first one installed rather than a
    duplicate stacked on top of it. The whole palette goes in, rather than
    only what the bar that asked for it wanted, so that what is installed does
    not depend on which bar was built first.
    """
    global _provider
    if _provider is None:
        _provider = Gtk.CssProvider()
        _provider.load_from_string(stylesheet(load()))
        Gtk.StyleContext.add_provider_for_display(
            display, _provider, Gtk.STYLE_PROVIDER_PRIORITY_APPLICATION
        )
    return _provider
