"""The settings model: schema on one side, /etc/nixos JSON on the other.

Keys are addressed by dotted path ("hostName", "features.printing") because
that is how the presentation layer names them; the JSON on disk is nested,
because that is what the module system expects — /etc/nixos/flake.nix maps
mkDefault over the top level and the module system pushes it down to the
leaves, so `features` has to arrive as an object.
"""

import copy
import json

from . import paths


class Schema:
    """modules/options.nix, as generated by schema.nix."""

    def __init__(self, tree):
        self._tree = tree
        self._flat = {}
        self._flatten(tree, ())

    def _flatten(self, node, prefix):
        for name, value in node.items():
            key = prefix + (name,)
            if "type" in value:
                self._flat[".".join(key)] = value
            else:
                self._flatten(value, key)

    @classmethod
    def load(cls):
        with open(paths.SCHEMA, encoding="utf-8") as handle:
            return cls(json.load(handle))

    def __contains__(self, key):
        return key in self._flat

    def __getitem__(self, key):
        return self._flat[key]

    def keys(self):
        return self._flat.keys()

    def default(self, key):
        return self._flat[key]["default"]


class Settings:
    """Stored values plus the edits not yet applied."""

    def __init__(self, schema, stored):
        self.schema = schema
        self.stored = stored
        self.pending = {}

    @classmethod
    def load(cls, schema):
        try:
            with open(paths.SETTINGS, encoding="utf-8") as handle:
                stored = json.load(handle)
        except FileNotFoundError:
            # A machine configured entirely from defaults. Legitimate, and
            # the app is exactly how you would start filling it in.
            stored = {}
        except (OSError, ValueError) as error:
            raise SettingsError(f"{paths.SETTINGS} could not be read: {error}") from error
        if not isinstance(stored, dict):
            raise SettingsError(f"{paths.SETTINGS} does not contain a JSON object.")
        return cls(schema, stored)

    # ── reading ──────────────────────────────────────────────────────

    def stored_value(self, key, missing=None):
        node = self.stored
        for part in key.split("."):
            if not isinstance(node, dict) or part not in node:
                return missing
            node = node[part]
        return node

    def is_stored(self, key):
        sentinel = object()
        return self.stored_value(key, sentinel) is not sentinel

    def effective(self, key):
        """What the system would use: pending edit, else file, else default."""
        if key in self.pending:
            return self.pending[key]
        sentinel = object()
        value = self.stored_value(key, sentinel)
        if value is not sentinel:
            return value
        return self.schema.default(key)

    def applied(self, key):
        """What the system uses now, ignoring unapplied edits."""
        sentinel = object()
        value = self.stored_value(key, sentinel)
        return self.schema.default(key) if value is sentinel else value

    # ── writing ──────────────────────────────────────────────────────

    def set(self, key, value):
        if value == self.applied(key):
            self.pending.pop(key, None)
        else:
            self.pending[key] = value

    @property
    def dirty(self):
        return bool(self.pending)

    def diff(self):
        """[(key, old, new)] for the review dialog, in a stable order."""
        return [(key, self.applied(key), self.pending[key]) for key in sorted(self.pending)]

    def to_json(self):
        """The new file contents.

        Built from a copy of what is on disk rather than from the schema, so
        keys this app does not know about — a newer option, something added
        by hand — survive a round trip untouched. Values equal to their
        default are not added, but ones already written out are left alone:
        removing a line nobody asked to remove is its own surprise.
        """
        result = copy.deepcopy(self.stored)
        for key, value in self.pending.items():
            parts = key.split(".")
            node = result
            for part in parts[:-1]:
                child = node.get(part)
                if not isinstance(child, dict):
                    child = {}
                    node[part] = child
                node = child
            node[parts[-1]] = value
        return result

    def serialize(self):
        return json.dumps(self.to_json(), indent=2, sort_keys=True) + "\n"

    def mark_applied(self):
        self.stored = self.to_json()
        self.pending.clear()


class SettingsError(Exception):
    pass


def format_value(value):
    """A value as the review dialog and the read-only rows should show it."""
    if isinstance(value, bool):
        return "on" if value else "off"
    if isinstance(value, list):
        return ", ".join(str(item) for item in value) if value else "(none)"
    if value is None:
        return "(unset)"
    return str(value)
