"""The settings model: schema on one side, /etc/nixos JSON on the other.

Keys are addressed by dotted path ("hostName", "features.printing") because
that is how the presentation layer names them; the JSON on disk is nested,
because that is what the module system expects — /etc/nixos/flake.nix maps
mkDefault over the top level and the module system pushes it down to the
leaves, so `features` has to arrive as an object.
"""

from __future__ import annotations

import copy
import enum
import json
from collections.abc import Iterator, KeysView
from typing import Final, Literal

from . import paths
from .datatypes import JSONObject, MalformedError, SchemaEntry, SettingValue, narrow_schema_entry


class _Absent(enum.Enum):
    """The type of MISSING, so that it narrows.

    A one-member enum rather than object(): `is not MISSING` then removes
    Literal[MISSING] from the union, and a value that is genuinely null in
    the settings file stays distinguishable from one that is not there —
    which for an option whose default is not null is a real difference.
    """

    TOKEN = enum.auto()


MISSING: Final = _Absent.TOKEN
type Missing = Literal[_Absent.TOKEN]


class Schema:
    """modules/options.nix, as generated by schema.nix."""

    def __init__(self, tree: JSONObject) -> None:
        self._flat: dict[str, SchemaEntry] = dict(_flatten(tree, ()))

    @classmethod
    def load(cls) -> Schema:
        with open(paths.SCHEMA, encoding="utf-8") as handle:
            tree = json.load(handle)
        if not isinstance(tree, dict):
            raise MalformedError(f"{paths.SCHEMA} does not contain a JSON object.")
        return cls(tree)

    def __contains__(self, key: str) -> bool:
        return key in self._flat

    def __getitem__(self, key: str) -> SchemaEntry:
        return self._flat[key]

    def keys(self) -> KeysView[str]:
        return self._flat.keys()

    def __iter__(self) -> Iterator[str]:
        return iter(self._flat)

    def default(self, key: str) -> SettingValue:
        return self._flat[key]["default"]


def _flatten(node: JSONObject, prefix: tuple[str, ...]) -> Iterator[tuple[str, SchemaEntry]]:
    """Dotted key to entry, for every leaf of the schema tree.

    A node carrying "type" is an option; anything else is a group to recurse
    into, which in practice means only `features`.
    """
    for name, value in node.items():
        key = (*prefix, name)
        dotted = ".".join(key)
        if isinstance(value, dict) and "type" in value:
            yield dotted, narrow_schema_entry(f"{dotted} in the schema", value)
        elif isinstance(value, dict):
            yield from _flatten(value, key)
        else:
            raise MalformedError(f"{dotted} in the schema is not an option or a group.")


class Settings:
    """Stored values plus the edits not yet applied."""

    def __init__(self, schema: Schema, stored: JSONObject) -> None:
        self.schema = schema
        self.stored = stored
        self.pending: dict[str, SettingValue] = {}

    @classmethod
    def load(cls, schema: Schema) -> Settings:
        try:
            with open(paths.SETTINGS, encoding="utf-8") as handle:
                stored = json.load(handle)
        except FileNotFoundError:
            # A machine configured entirely from defaults. Legitimate, and
            # the app is exactly how you would start filling it in.
            stored = {}
        except (OSError, ValueError) as error:
            raise SettingsError(f"{paths.SETTINGS} could not be read: {error}") from error
        if not isinstance(stored, dict):
            raise SettingsError(f"{paths.SETTINGS} does not contain a JSON object.")
        return cls(schema, stored)

    # ── reading ──────────────────────────────────────────────────────

    def stored_value(self, key: str) -> SettingValue | Missing:
        """What the file says, or MISSING if it does not mention this key."""
        node: SettingValue = self.stored
        for part in key.split("."):
            if not isinstance(node, dict) or part not in node:
                return MISSING
            node = node[part]
        return node

    def is_stored(self, key: str) -> bool:
        return self.stored_value(key) is not MISSING

    def effective(self, key: str) -> SettingValue:
        """What the system would use: pending edit, else file, else default."""
        if key in self.pending:
            return self.pending[key]
        return self.applied(key)

    def applied(self, key: str) -> SettingValue:
        """What the system uses now, ignoring unapplied edits."""
        value = self.stored_value(key)
        return self.schema.default(key) if value is MISSING else value

    # ── writing ──────────────────────────────────────────────────────

    def set(self, key: str, value: SettingValue) -> None:
        if value == self.applied(key):
            self.pending.pop(key, None)
        else:
            self.pending[key] = value

    @property
    def dirty(self) -> bool:
        return bool(self.pending)

    def diff(self) -> list[tuple[str, SettingValue, SettingValue]]:
        """[(key, old, new)] for the review dialog, in a stable order."""
        return [(key, self.applied(key), self.pending[key]) for key in sorted(self.pending)]

    def to_json(self) -> JSONObject:
        """The new file contents.

        Built from a copy of what is on disk rather than from the schema, so
        keys this app does not know about — a newer option, something added
        by hand — survive a round trip untouched. Values equal to their
        default are not added, but ones already written out are left alone:
        removing a line nobody asked to remove is its own surprise.
        """
        result: JSONObject = copy.deepcopy(self.stored)
        for key, value in self.pending.items():
            parts = key.split(".")
            node = result
            for part in parts[:-1]:
                child = node.get(part)
                if not isinstance(child, dict):
                    child = {}
                    node[part] = child
                node = child
            node[parts[-1]] = value
        return result

    def serialize(self) -> str:
        return json.dumps(self.to_json(), indent=2, sort_keys=True) + "\n"

    def mark_applied(self) -> None:
        self.stored = self.to_json()
        self.pending.clear()


class SettingsError(Exception):
    pass


def format_value(value: SettingValue) -> str:
    """A value as the review dialog and the read-only rows should show it."""
    if isinstance(value, bool):
        return "on" if value else "off"
    if isinstance(value, list):
        return ", ".join(str(item) for item in value) if value else "(none)"
    if value is None:
        return "(unset)"
    # An empty string is how "no wallpaper" and its like are written. Shown
    # as nothing at all it would leave the review dialog with a blank on one
    # side of the arrow and no way to tell which side.
    if value == "":
        return "(none)"
    return str(value)
